version: "3.8"

services:
  register:
    build: register
    container_name: register
    environment:
      name: register
  api:
    build: api
    container_name: api
    ports :
      - "80:5000"
    environment:
      name : api
