version: "3.8"

services:
  register:
    build: register
    container_name: register
    environment:
      name: register
    networks:
      - services

  api:
    build: api
    container_name: api
    ports :
      - "80:5000"
    environment:
      name : api
    networks:
      - services

  registration:
    build: registration
    container_name: registration
    environment:
      name: registration
    networks:
      - services
      - db-user

  oauth:
    build: oauth
    container_name: oauth
    environment:
      name: oauth
    networks:
      - services
      - db-user

  deploy:
    build: deploy
    container_name: deploy
    environment:
      name: deploy
    networks:
      - services
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  image:
    build: image
    container_name: image
    environment:
      name: image
    networks:
      - services
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"

  db-user:
    image: mongo:latest
    container_name: mongo
    volumes:
      - DB-user:/data/db
    networks:
      - db-user
    ports:
      - "27017:27017"

networks:
  services:
  db-user:

volumes:
  DB-user: